# Generated by Django 5.0.1 on 2024-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='tags',
            field=models.ManyToManyField(to='accessories.tag'),
        ),
    ]
