# Generated by Django 5.0.1 on 2024-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0004_rename_type_accessories_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='detail',
            field=models.CharField(max_length=500),
        ),
    ]
